# Configuration options for cvmfs-servermon api
# Available options are:
#   serveralias <aliasname>=<fully.qualified.domain.name[:port][/subdirectory]>
#     Default: serveralias local=localhost
#   excluderepo <fully.qualified.repository.name>
#   disabletest <testname> [<repo1> <repo2> ...]
#     Where:
#       <testname> is updated, gc, geo, whitelist, or check
#       <repo1> <repo2> ... are optional space-separated fully qualified
#         repository names.  If given, the test is disabled only for those
#         repositories.  If omitted, the test is disabled for all repositories
#   updated-slowrepo <fully.qualified.repository.name>
#   limit <testname>-<testlevel>=<limit>
#     Where:
#       <testname> is updated, gc, or whitelist
#       <testlevel> is warning or critical
#       <limit> is the limit to set, in the unit of the specific test;
#               updated and whitelist are in hours, gc is in days
#           Defaults are:
#               limit updated-multiplier=1.1
#               limit updated-warning=8
#               limit updated-critical=24
#               limit gc-warning=10
#               limit gc-critical=20
#               limit whitelist-warning=48
